[2023-05-06T00:25:14.414+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-06T00:24:47.766343+00:00 [queued]>
[2023-05-06T00:25:14.421+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-06T00:24:47.766343+00:00 [queued]>
[2023-05-06T00:25:14.421+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-06T00:25:14.430+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): machine_learning_task> on 2023-05-06 00:24:47.766343+00:00
[2023-05-06T00:25:14.441+0000] {standard_task_runner.py:57} INFO - Started process 479 to run task
[2023-05-06T00:25:14.446+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'machine_learning_task', 'manual__2023-05-06T00:24:47.766343+00:00', '--job-id', '622', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmp6ibdp9bu']
[2023-05-06T00:25:14.447+0000] {standard_task_runner.py:85} INFO - Job 622: Subtask machine_learning_task
[2023-05-06T00:25:14.493+0000] {task_command.py:410} INFO - Running <TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-06T00:24:47.766343+00:00 [running]> on host 29d8848a13b4
[2023-05-06T00:25:14.560+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lequanghop844@gmail.com' AIRFLOW_CTX_DAG_OWNER='Felix Le' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='machine_learning_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-06T00:24:47.766343+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-06T00:24:47.766343+00:00'
[2023-05-06T00:25:15.004+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/joblib/parallel.py:776: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  **self._backend_args)

[2023-05-06T00:25:15.005+0000] {logging_mixin.py:149} INFO - Fitting 3 folds for each of 1 candidates, totalling 3 fits
[2023-05-06T00:25:34.912+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 18s
[2023-05-06T00:25:34.962+0000] {logging_mixin.py:149} INFO - 39/92 [===========>..................] - ETA: 0s 
[2023-05-06T00:25:35.012+0000] {logging_mixin.py:149} INFO - 79/92 [========================>.....] - ETA: 0s
[2023-05-06T00:25:35.029+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 0s 1ms/step
[2023-05-06T00:25:35.046+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=  20.0s
[2023-05-06T00:25:56.741+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 17s
[2023-05-06T00:25:56.792+0000] {logging_mixin.py:149} INFO - 37/92 [===========>..................] - ETA: 0s 
[2023-05-06T00:25:56.843+0000] {logging_mixin.py:149} INFO - 74/92 [=======================>......] - ETA: 0s
[2023-05-06T00:25:56.867+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 0s 1ms/step
[2023-05-06T00:25:56.879+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=  21.8s
[2023-05-06T00:26:18.204+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 16s
[2023-05-06T00:26:18.255+0000] {logging_mixin.py:149} INFO - 31/92 [=========>....................] - ETA: 0s 
[2023-05-06T00:26:18.307+0000] {logging_mixin.py:149} INFO - 62/92 [===================>..........] - ETA: 0s
[2023-05-06T00:26:18.354+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 0s 2ms/step
[2023-05-06T00:26:18.366+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=  21.5s
[2023-05-06T00:26:47.396+0000] {logging_function.py:9} INFO - Grid search results: 
[2023-05-06T00:26:47.398+0000] {logging_function.py:11} INFO - Params: {'batch_size': 128, 'dropout': 0.4, 'epochs': 50, 'learning_rate': 0.0001, 'num_units': 32} - Mean test score: -0.0018426606970117908, Std test score: 9.032559419453045e-05
[2023-05-06T00:26:47.402+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/fetching_best_model.py", line 50, in best_model_search
    best_model.model.save('/Users/hople/Desktop/Work_sample/dags/model/best_lstm_model.keras')
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 513, in recursive_create_dir_v2
    _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.PermissionDeniedError: /Users/hople/Desktop/Work_sample/dags; Permission denied
[2023-05-06T00:26:47.433+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=machine_learning_task, execution_date=20230506T002447, start_date=20230506T002514, end_date=20230506T002647
[2023-05-06T00:26:47.451+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 622 for task machine_learning_task (/Users/hople/Desktop/Work_sample/dags; Permission denied; 479)
[2023-05-06T00:26:47.854+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-06T00:26:47.878+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
