[2023-05-07T22:35:07.447+0000] {processor.py:156} INFO - Started process (PID=138) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:35:07.450+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:35:07.454+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:35:07.453+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:35:07.788+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:35:07.801+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.362 seconds
[2023-05-07T22:35:39.782+0000] {processor.py:156} INFO - Started process (PID=251) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:35:39.785+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:35:39.786+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:35:39.786+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:35:40.032+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:35:40.044+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.269 seconds
[2023-05-07T22:36:12.059+0000] {processor.py:156} INFO - Started process (PID=366) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:36:12.061+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:36:12.061+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:36:12.061+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:36:12.460+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:36:12.480+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.424 seconds
[2023-05-07T22:36:44.417+0000] {processor.py:156} INFO - Started process (PID=489) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:36:44.419+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:36:44.420+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:36:44.419+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:36:44.682+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:36:44.695+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.281 seconds
[2023-05-07T22:37:15.854+0000] {processor.py:156} INFO - Started process (PID=612) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:37:15.856+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:37:15.856+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:37:15.856+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:37:16.126+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:37:16.138+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.286 seconds
[2023-05-07T22:37:46.486+0000] {processor.py:156} INFO - Started process (PID=744) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:37:46.487+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:37:46.489+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:37:46.489+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:37:46.813+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:37:46.802+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T22:37:46.816+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:37:46.869+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.387 seconds
[2023-05-07T22:38:16.946+0000] {processor.py:156} INFO - Started process (PID=849) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:38:16.948+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:38:16.949+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:38:16.949+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:38:17.219+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:38:17.216+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/Users/hople/Desktop/Work_sample/dags/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hople/Desktop/Work_sample/dags/data/symbols_valid_meta.csv'
[2023-05-07T22:38:17.220+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:38:17.238+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.296 seconds
[2023-05-07T22:38:47.312+0000] {processor.py:156} INFO - Started process (PID=963) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:38:47.314+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:38:47.315+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:38:47.315+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:38:47.536+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:38:47.534+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/Users/hople/Desktop/Work_sample/dags/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hople/Desktop/Work_sample/dags/data/symbols_valid_meta.csv'
[2023-05-07T22:38:47.537+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:38:47.551+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.244 seconds
[2023-05-07T22:39:18.059+0000] {processor.py:156} INFO - Started process (PID=1077) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:39:18.061+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:39:18.062+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:39:18.062+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:39:18.325+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:39:18.321+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/Users/hople/Desktop/Work_sample/dags/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hople/Desktop/Work_sample/dags/data/symbols_valid_meta.csv'
[2023-05-07T22:39:18.326+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:39:18.340+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.285 seconds
[2023-05-07T22:39:48.470+0000] {processor.py:156} INFO - Started process (PID=1200) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:39:48.471+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:39:48.471+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:39:48.471+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:39:48.736+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:39:48.734+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('opt/airflow/dags/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/data/symbols_valid_meta.csv'
[2023-05-07T22:39:48.737+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:39:48.751+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.285 seconds
[2023-05-07T22:40:19.023+0000] {processor.py:156} INFO - Started process (PID=1314) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:40:19.025+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:40:19.026+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:40:19.026+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:40:19.443+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:40:19.431+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('opt/airflow/dags/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/data/symbols_valid_meta.csv'
[2023-05-07T22:40:19.446+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:40:19.472+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.453 seconds
[2023-05-07T22:40:50.042+0000] {processor.py:156} INFO - Started process (PID=1428) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:40:50.044+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:40:50.045+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:40:50.045+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:40:50.309+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:40:50.305+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('opt/airflow/dags/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/data/symbols_valid_meta.csv'
[2023-05-07T22:40:50.309+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:40:50.326+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.289 seconds
[2023-05-07T22:44:18.192+0000] {processor.py:156} INFO - Started process (PID=138) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:44:18.195+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:44:18.196+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:44:18.196+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:44:18.494+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:44:18.490+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('opt/airflow/dags/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/data/symbols_valid_meta.csv'
[2023-05-07T22:44:18.495+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:44:18.514+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.325 seconds
[2023-05-07T22:44:48.717+0000] {processor.py:156} INFO - Started process (PID=235) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:44:48.719+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:44:48.719+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:44:48.719+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:44:49.003+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:44:48.999+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('opt/airflow/dags/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/data/symbols_valid_meta.csv'
[2023-05-07T22:44:49.004+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:44:49.030+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.315 seconds
[2023-05-07T22:45:20.006+0000] {processor.py:156} INFO - Started process (PID=357) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:45:20.008+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:45:20.009+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:45:20.009+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:45:20.248+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:45:20.246+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('opt/airflow/dags/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/data/symbols_valid_meta.csv'
[2023-05-07T22:45:20.249+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:45:20.265+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.262 seconds
[2023-05-07T22:45:50.850+0000] {processor.py:156} INFO - Started process (PID=471) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:45:50.851+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:45:50.852+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:45:50.852+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:45:51.090+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:45:51.087+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('opt/airflow/dags/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/data/symbols_valid_meta.csv'
[2023-05-07T22:45:51.091+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:45:51.105+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.258 seconds
[2023-05-07T22:46:21.562+0000] {processor.py:156} INFO - Started process (PID=585) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:46:21.564+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:46:21.565+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:46:21.564+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:46:21.801+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:46:21.799+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('opt/airflow/dags/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/data/symbols_valid_meta.csv'
[2023-05-07T22:46:21.802+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:46:21.819+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.260 seconds
[2023-05-07T22:46:51.971+0000] {processor.py:156} INFO - Started process (PID=699) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:46:51.973+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:46:51.974+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:46:51.974+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:46:52.216+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:46:52.213+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('opt/airflow/dags/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/data/symbols_valid_meta.csv'
[2023-05-07T22:46:52.216+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:46:52.231+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.263 seconds
[2023-05-07T22:47:22.725+0000] {processor.py:156} INFO - Started process (PID=813) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:47:22.726+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:47:22.727+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:47:22.727+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:47:22.979+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:47:22.975+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('opt/airflow/dags/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/data/symbols_valid_meta.csv'
[2023-05-07T22:47:22.980+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:47:22.994+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.272 seconds
[2023-05-07T22:47:53.463+0000] {processor.py:156} INFO - Started process (PID=929) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:47:53.464+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:47:53.465+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:47:53.465+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:47:53.713+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:47:53.711+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('opt/airflow/dags/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/data/symbols_valid_meta.csv'
[2023-05-07T22:47:53.714+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:47:53.729+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.270 seconds
[2023-05-07T22:51:37.911+0000] {processor.py:156} INFO - Started process (PID=138) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:51:37.914+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:51:37.917+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:51:37.916+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:51:38.448+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:51:38.442+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('opt/airflow/dags/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/data/symbols_valid_meta.csv'
[2023-05-07T22:51:38.449+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:51:38.473+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.565 seconds
[2023-05-07T22:52:09.012+0000] {processor.py:156} INFO - Started process (PID=190) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:52:09.014+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:52:09.015+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:52:09.015+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:52:09.328+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:52:09.325+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('opt/airflow/dags/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/data/symbols_valid_meta.csv'
[2023-05-07T22:52:09.328+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:52:09.345+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.337 seconds
[2023-05-07T22:52:39.895+0000] {processor.py:156} INFO - Started process (PID=251) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:52:39.897+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:52:39.898+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:52:39.897+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:52:40.170+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:52:40.166+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('opt/airflow/dags/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'opt/airflow/dags/data/symbols_valid_meta.csv'
[2023-05-07T22:52:40.171+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:52:40.192+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.299 seconds
[2023-05-07T22:53:10.549+0000] {processor.py:156} INFO - Started process (PID=320) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:53:10.552+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:53:10.553+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:53:10.553+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:53:10.797+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:53:10.794+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T22:53:10.798+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:53:10.815+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.272 seconds
[2023-05-07T22:53:41.417+0000] {processor.py:156} INFO - Started process (PID=381) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:53:41.419+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:53:41.421+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:53:41.420+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:53:41.665+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:53:41.662+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T22:53:41.666+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:53:41.688+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.280 seconds
[2023-05-07T22:54:11.923+0000] {processor.py:156} INFO - Started process (PID=442) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:54:11.926+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:54:11.928+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:54:11.927+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:54:12.153+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:54:12.151+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T22:54:12.154+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:54:12.169+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.252 seconds
[2023-05-07T22:54:42.742+0000] {processor.py:156} INFO - Started process (PID=503) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:54:42.745+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:54:42.746+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:54:42.746+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:54:42.975+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:54:42.972+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T22:54:42.976+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:54:42.990+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.254 seconds
[2023-05-07T22:55:13.255+0000] {processor.py:156} INFO - Started process (PID=564) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:55:13.258+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:55:13.259+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:55:13.259+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:55:13.482+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:55:13.479+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T22:55:13.483+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:55:13.496+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.246 seconds
[2023-05-07T22:55:44.211+0000] {processor.py:156} INFO - Started process (PID=625) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:55:44.214+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:55:44.216+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:55:44.216+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:55:44.446+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:55:44.444+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T22:55:44.447+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:55:44.461+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.258 seconds
[2023-05-07T22:56:14.739+0000] {processor.py:156} INFO - Started process (PID=686) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:56:14.742+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:56:14.744+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:56:14.744+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:56:14.970+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:56:14.968+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T22:56:14.972+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:56:14.985+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.252 seconds
[2023-05-07T22:56:45.243+0000] {processor.py:156} INFO - Started process (PID=746) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:56:45.245+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:56:45.246+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:56:45.246+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:56:45.483+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:56:45.481+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T22:56:45.484+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:56:45.498+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.261 seconds
[2023-05-07T22:57:15.765+0000] {processor.py:156} INFO - Started process (PID=807) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:57:15.767+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:57:15.770+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:57:15.770+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:57:16.035+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:57:16.033+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T22:57:16.036+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:57:16.050+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.292 seconds
[2023-05-07T22:57:46.522+0000] {processor.py:156} INFO - Started process (PID=868) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:57:46.525+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:57:46.526+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:57:46.526+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:57:46.766+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:57:46.764+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T22:57:46.767+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:57:46.781+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.265 seconds
[2023-05-07T22:58:17.241+0000] {processor.py:156} INFO - Started process (PID=929) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:58:17.244+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:58:17.246+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:58:17.246+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:58:17.508+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:58:17.505+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T22:58:17.508+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:58:17.524+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.287 seconds
[2023-05-07T22:58:48.080+0000] {processor.py:156} INFO - Started process (PID=990) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:58:48.082+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:58:48.084+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:58:48.083+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:58:48.314+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:58:48.312+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T22:58:48.315+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:58:48.329+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.254 seconds
[2023-05-07T22:59:18.905+0000] {processor.py:156} INFO - Started process (PID=1051) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:59:18.907+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:59:18.909+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:59:18.909+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:59:19.133+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:59:19.130+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T22:59:19.134+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:59:19.147+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.248 seconds
[2023-05-07T22:59:49.718+0000] {processor.py:156} INFO - Started process (PID=1112) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:59:49.721+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T22:59:49.722+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:59:49.722+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:59:49.953+0000] {logging_mixin.py:149} INFO - [2023-05-07T22:59:49.950+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T22:59:49.953+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T22:59:49.967+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.256 seconds
[2023-05-07T23:04:01.444+0000] {processor.py:156} INFO - Started process (PID=69) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:04:01.446+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:04:01.448+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:04:01.448+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:04:01.791+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:04:01.787+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:04:01.792+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:04:01.814+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.376 seconds
[2023-05-07T23:04:32.024+0000] {processor.py:156} INFO - Started process (PID=122) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:04:32.025+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:04:32.025+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:04:32.025+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:04:32.243+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:04:32.241+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:04:32.244+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:04:32.258+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.237 seconds
[2023-05-07T23:05:02.463+0000] {processor.py:156} INFO - Started process (PID=175) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:05:02.464+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:05:02.465+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:05:02.465+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:05:02.679+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:05:02.677+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:05:02.680+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:05:02.695+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.235 seconds
[2023-05-07T23:05:32.918+0000] {processor.py:156} INFO - Started process (PID=228) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:05:32.919+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:05:32.920+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:05:32.920+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:05:33.132+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:05:33.130+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:05:33.133+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:05:33.149+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.234 seconds
[2023-05-07T23:06:03.336+0000] {processor.py:156} INFO - Started process (PID=281) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:06:03.337+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:06:03.338+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:06:03.338+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:06:03.560+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:06:03.558+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:06:03.561+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:06:03.575+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.241 seconds
[2023-05-07T23:06:33.810+0000] {processor.py:156} INFO - Started process (PID=334) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:06:33.811+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:06:33.812+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:06:33.812+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:06:34.024+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:06:34.021+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:06:34.025+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:06:34.039+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.231 seconds
[2023-05-07T23:07:04.243+0000] {processor.py:156} INFO - Started process (PID=387) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:07:04.244+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:07:04.245+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:07:04.245+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:07:04.453+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:07:04.451+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:07:04.454+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:07:04.468+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.228 seconds
[2023-05-07T23:07:34.515+0000] {processor.py:156} INFO - Started process (PID=440) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:07:34.516+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:07:34.518+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:07:34.517+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:07:34.756+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:07:34.754+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:07:34.757+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:07:34.772+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.260 seconds
[2023-05-07T23:08:05.713+0000] {processor.py:156} INFO - Started process (PID=493) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:08:05.715+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:08:05.716+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:08:05.716+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:08:05.937+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:08:05.935+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:08:05.938+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:08:05.952+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.243 seconds
[2023-05-07T23:08:36.979+0000] {processor.py:156} INFO - Started process (PID=546) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:08:36.981+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:08:36.982+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:08:36.982+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:08:37.211+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:08:37.208+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:08:37.212+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:08:37.230+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.254 seconds
[2023-05-07T23:09:07.553+0000] {processor.py:156} INFO - Started process (PID=598) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:09:07.555+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:09:07.557+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:09:07.557+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:09:07.880+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:09:07.877+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:09:07.882+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:09:07.905+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.355 seconds
[2023-05-07T23:09:38.053+0000] {processor.py:156} INFO - Started process (PID=644) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:09:38.055+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:09:38.056+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:09:38.056+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:09:38.373+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:09:38.368+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:09:38.374+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:09:38.398+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.347 seconds
[2023-05-07T23:10:09.223+0000] {processor.py:156} INFO - Started process (PID=697) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:10:09.224+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:10:09.225+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:10:09.225+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:10:09.491+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:10:09.488+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:10:09.491+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:10:09.508+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.287 seconds
[2023-05-07T23:10:40.253+0000] {processor.py:156} INFO - Started process (PID=750) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:10:40.254+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:10:40.255+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:10:40.255+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:10:40.520+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:10:40.517+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:10:40.521+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:10:40.536+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.286 seconds
[2023-05-07T23:11:11.306+0000] {processor.py:156} INFO - Started process (PID=803) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:11:11.307+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:11:11.308+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:11:11.308+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:11:11.573+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:11:11.571+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:11:11.575+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:11:11.590+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.286 seconds
[2023-05-07T23:11:42.330+0000] {processor.py:156} INFO - Started process (PID=857) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:11:42.331+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:11:42.332+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:11:42.332+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:11:42.601+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:11:42.598+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:11:42.602+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:11:42.619+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.294 seconds
[2023-05-07T23:12:13.414+0000] {processor.py:156} INFO - Started process (PID=910) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:12:13.416+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:12:13.417+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:12:13.417+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:12:13.675+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:12:13.672+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:12:13.676+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:12:13.691+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.283 seconds
[2023-05-07T23:12:44.491+0000] {processor.py:156} INFO - Started process (PID=963) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:12:44.493+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:12:44.495+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:12:44.495+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:12:44.746+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:12:44.743+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:12:44.747+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:12:44.762+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.277 seconds
[2023-05-07T23:13:15.462+0000] {processor.py:156} INFO - Started process (PID=1016) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:13:15.464+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:13:15.465+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:13:15.465+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:13:15.729+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:13:15.726+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:13:15.730+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:13:15.745+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.288 seconds
[2023-05-07T23:13:46.476+0000] {processor.py:156} INFO - Started process (PID=1069) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:13:46.477+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:13:46.479+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:13:46.479+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:13:46.735+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:13:46.733+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:13:46.736+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:13:46.752+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.282 seconds
[2023-05-07T23:14:16.802+0000] {processor.py:156} INFO - Started process (PID=1122) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:14:16.803+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:14:16.803+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:14:16.803+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:14:17.067+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:14:17.064+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:14:17.068+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:14:17.084+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.285 seconds
[2023-05-07T23:14:48.088+0000] {processor.py:156} INFO - Started process (PID=1183) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:14:48.089+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:14:48.090+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:14:48.090+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:14:48.321+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:14:48.318+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:14:48.322+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:14:48.335+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.250 seconds
[2023-05-07T23:15:19.244+0000] {processor.py:156} INFO - Started process (PID=1236) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:15:19.245+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:15:19.246+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:15:19.246+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:15:19.512+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:15:19.510+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:15:19.513+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:15:19.527+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.286 seconds
[2023-05-07T23:15:50.410+0000] {processor.py:156} INFO - Started process (PID=1289) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:15:50.412+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:15:50.413+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:15:50.412+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:15:50.638+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:15:50.636+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:15:50.639+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:15:50.652+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.245 seconds
[2023-05-07T23:16:21.502+0000] {processor.py:156} INFO - Started process (PID=1342) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:16:21.503+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:16:21.504+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:16:21.504+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:16:21.747+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:16:21.745+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:16:21.748+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:16:21.762+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.263 seconds
[2023-05-07T23:16:52.606+0000] {processor.py:156} INFO - Started process (PID=1395) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:16:52.608+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:16:52.609+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:16:52.609+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:16:52.819+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:16:52.817+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:16:52.820+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:16:52.833+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.229 seconds
[2023-05-07T23:21:22.332+0000] {processor.py:156} INFO - Started process (PID=77) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:21:22.339+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:21:22.344+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:21:22.344+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:21:23.426+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:21:23.416+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:21:23.430+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:21:23.500+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 1.176 seconds
[2023-05-07T23:21:53.727+0000] {processor.py:156} INFO - Started process (PID=129) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:21:53.728+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:21:53.729+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:21:53.729+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:21:54.098+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:21:54.093+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/utils/data_processing.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/data/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/data/symbols_valid_meta.csv'
[2023-05-07T23:21:54.100+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:21:54.125+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.402 seconds
[2023-05-07T23:22:24.350+0000] {processor.py:156} INFO - Started process (PID=199) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:22:24.354+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:22:24.356+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:22:24.356+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:22:24.628+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:22:24.640+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.295 seconds
[2023-05-07T23:22:54.823+0000] {processor.py:156} INFO - Started process (PID=260) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:22:54.826+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:22:54.827+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:22:54.827+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:22:55.130+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:22:55.141+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.323 seconds
[2023-05-07T23:23:25.848+0000] {processor.py:156} INFO - Started process (PID=313) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:23:25.850+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:23:25.852+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:23:25.851+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:23:26.148+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:23:26.159+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.315 seconds
[2023-05-07T23:23:56.389+0000] {processor.py:156} INFO - Started process (PID=373) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:23:56.392+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:23:56.393+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:23:56.393+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:23:56.636+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:23:56.647+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.264 seconds
[2023-05-07T23:24:26.924+0000] {processor.py:156} INFO - Started process (PID=434) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:24:26.926+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:24:26.927+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:24:26.927+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:24:27.278+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:24:27.290+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.370 seconds
[2023-05-07T23:24:57.678+0000] {processor.py:156} INFO - Started process (PID=513) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:24:57.681+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:24:57.682+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:24:57.682+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:24:57.956+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:24:57.975+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.301 seconds
[2023-05-07T23:26:21.371+0000] {processor.py:156} INFO - Started process (PID=76) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:26:21.373+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:26:21.374+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:26:21.374+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:26:21.710+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:26:21.719+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.351 seconds
[2023-05-07T23:26:53.213+0000] {processor.py:156} INFO - Started process (PID=137) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:26:53.215+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:26:53.216+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:26:53.216+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:26:53.573+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:26:53.583+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.372 seconds
[2023-05-07T23:27:25.458+0000] {processor.py:156} INFO - Started process (PID=219) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:27:25.460+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:27:25.461+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:27:25.461+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:27:25.817+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:27:25.828+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.373 seconds
[2023-05-07T23:27:57.421+0000] {processor.py:156} INFO - Started process (PID=279) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:27:57.423+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:27:57.424+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:27:57.424+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:27:57.753+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:27:57.763+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.346 seconds
[2023-05-07T23:28:29.392+0000] {processor.py:156} INFO - Started process (PID=341) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:28:29.393+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:28:29.394+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:28:29.394+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:28:29.711+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:28:29.720+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.331 seconds
[2023-05-07T23:29:01.276+0000] {processor.py:156} INFO - Started process (PID=405) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:29:01.277+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:29:01.278+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:29:01.278+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:29:01.613+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:29:01.622+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.349 seconds
[2023-05-07T23:29:09.780+0000] {processor.py:156} INFO - Started process (PID=414) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:29:09.782+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:29:09.783+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:29:09.783+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:29:09.787+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:29:09.787+0000] {dagbag.py:327} INFO - File /opt/airflow/dags/utils/data_processing.py assumed to contain no DAGs. Skipping.
[2023-05-07T23:29:09.788+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:29:09.809+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.035 seconds
[2023-05-07T23:29:39.911+0000] {processor.py:156} INFO - Started process (PID=451) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:29:39.913+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:29:39.914+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:29:39.914+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:29:39.917+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:29:39.917+0000] {dagbag.py:327} INFO - File /opt/airflow/dags/utils/data_processing.py assumed to contain no DAGs. Skipping.
[2023-05-07T23:29:39.918+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:29:39.939+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.033 seconds
[2023-05-07T23:30:10.064+0000] {processor.py:156} INFO - Started process (PID=488) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:30:10.067+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:30:10.068+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:30:10.068+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:30:10.072+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:30:10.071+0000] {dagbag.py:327} INFO - File /opt/airflow/dags/utils/data_processing.py assumed to contain no DAGs. Skipping.
[2023-05-07T23:30:10.072+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:30:10.093+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.035 seconds
[2023-05-07T23:30:40.241+0000] {processor.py:156} INFO - Started process (PID=517) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:30:40.244+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:30:40.246+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:30:40.246+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:30:40.252+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:30:40.251+0000] {dagbag.py:327} INFO - File /opt/airflow/dags/utils/data_processing.py assumed to contain no DAGs. Skipping.
[2023-05-07T23:30:40.253+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:30:40.277+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.043 seconds
[2023-05-07T23:31:10.440+0000] {processor.py:156} INFO - Started process (PID=546) to work on /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:31:10.442+0000] {processor.py:799} INFO - Processing file /opt/airflow/dags/utils/data_processing.py for tasks to queue
[2023-05-07T23:31:10.443+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:31:10.443+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:31:10.447+0000] {logging_mixin.py:149} INFO - [2023-05-07T23:31:10.446+0000] {dagbag.py:327} INFO - File /opt/airflow/dags/utils/data_processing.py assumed to contain no DAGs. Skipping.
[2023-05-07T23:31:10.447+0000] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/data_processing.py
[2023-05-07T23:31:10.556+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/utils/data_processing.py took 0.122 seconds
