[2023-05-06T06:44:35.642+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-06T06:44:09.554400+00:00 [queued]>
[2023-05-06T06:44:35.649+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-06T06:44:09.554400+00:00 [queued]>
[2023-05-06T06:44:35.649+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-06T06:44:35.657+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): machine_learning_task> on 2023-05-06 06:44:09.554400+00:00
[2023-05-06T06:44:35.667+0000] {standard_task_runner.py:57} INFO - Started process 20093 to run task
[2023-05-06T06:44:35.671+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'machine_learning_task', 'manual__2023-05-06T06:44:09.554400+00:00', '--job-id', '1020', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpc0hd8he9']
[2023-05-06T06:44:35.672+0000] {standard_task_runner.py:85} INFO - Job 1020: Subtask machine_learning_task
[2023-05-06T06:44:35.719+0000] {task_command.py:410} INFO - Running <TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-06T06:44:09.554400+00:00 [running]> on host 03dea93b6a82
[2023-05-06T06:44:35.782+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lequanghop844@gmail.com' AIRFLOW_CTX_DAG_OWNER='Felix Le' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='machine_learning_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-06T06:44:09.554400+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-06T06:44:09.554400+00:00'
[2023-05-06T06:44:35.985+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/joblib/parallel.py:776: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  **self._backend_args)

[2023-05-06T06:44:35.999+0000] {logging_mixin.py:149} INFO - Fitting 3 folds for each of 1 candidates, totalling 3 fits
[2023-05-06T06:44:55.985+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 17s
[2023-05-06T06:44:56.035+0000] {logging_mixin.py:149} INFO - 36/92 [==========>...................] - ETA: 0s 
[2023-05-06T06:44:56.086+0000] {logging_mixin.py:149} INFO - 78/92 [========================>.....] - ETA: 0s
[2023-05-06T06:44:56.103+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 0s 1ms/step
[2023-05-06T06:44:56.120+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=  20.1s
[2023-05-06T06:45:17.553+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 16s
[2023-05-06T06:45:17.604+0000] {logging_mixin.py:149} INFO - 26/92 [=======>......................] - ETA: 0s 
[2023-05-06T06:45:17.655+0000] {logging_mixin.py:149} INFO - 62/92 [===================>..........] - ETA: 0s
[2023-05-06T06:45:17.695+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 0s 2ms/step
[2023-05-06T06:45:17.706+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=  21.6s
[2023-05-06T06:45:37.622+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 20s
[2023-05-06T06:45:37.673+0000] {logging_mixin.py:149} INFO - 35/92 [==========>...................] - ETA: 0s 
[2023-05-06T06:45:37.724+0000] {logging_mixin.py:149} INFO - 64/92 [===================>..........] - ETA: 0s
[2023-05-06T06:45:37.772+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 0s 2ms/step
[2023-05-06T06:45:37.785+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=  20.1s
[2023-05-06T06:46:06.452+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/utils/logging_function.py", line 11, in logging_grid_search
    with open(path_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hople/Desktop/Work_sample/model/training_log/grid_seach.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/fetching_best_model.py", line 89, in best_model_search
    logging_grid_search(tempt)
  File "/opt/airflow/dags/utils/logging_function.py", line 15, in logging_grid_search
    df.to_csv(path_file , sep=',', index=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hople/Desktop/Work_sample/model/training_log/grid_seach.csv'
[2023-05-06T06:46:06.470+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=machine_learning_task, execution_date=20230506T064409, start_date=20230506T064435, end_date=20230506T064606
[2023-05-06T06:46:06.496+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1020 for task machine_learning_task ([Errno 2] No such file or directory: '/Users/hople/Desktop/Work_sample/model/training_log/grid_seach.csv'; 20093)
[2023-05-06T06:46:06.855+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-06T06:46:06.878+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
