[2023-05-06T00:29:56.410+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-06T00:29:25.007990+00:00 [queued]>
[2023-05-06T00:29:56.424+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-06T00:29:25.007990+00:00 [queued]>
[2023-05-06T00:29:56.426+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-06T00:29:56.445+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): machine_learning_task> on 2023-05-06 00:29:25.007990+00:00
[2023-05-06T00:29:56.466+0000] {standard_task_runner.py:57} INFO - Started process 4509 to run task
[2023-05-06T00:29:56.472+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'machine_learning_task', 'manual__2023-05-06T00:29:25.007990+00:00', '--job-id', '673', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmp9rbu_iwa']
[2023-05-06T00:29:56.473+0000] {standard_task_runner.py:85} INFO - Job 673: Subtask machine_learning_task
[2023-05-06T00:29:56.530+0000] {task_command.py:410} INFO - Running <TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-06T00:29:25.007990+00:00 [running]> on host 29d8848a13b4
[2023-05-06T00:29:56.617+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lequanghop844@gmail.com' AIRFLOW_CTX_DAG_OWNER='Felix Le' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='machine_learning_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-06T00:29:25.007990+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-06T00:29:25.007990+00:00'
[2023-05-06T00:29:56.867+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/joblib/parallel.py:776: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  **self._backend_args)

[2023-05-06T00:29:56.868+0000] {logging_mixin.py:149} INFO - Fitting 3 folds for each of 1 candidates, totalling 3 fits
[2023-05-06T00:30:30.063+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 40s
[2023-05-06T00:30:30.113+0000] {logging_mixin.py:149} INFO - 13/92 [===>..........................] - ETA: 0s 
[2023-05-06T00:30:30.164+0000] {logging_mixin.py:149} INFO - 29/92 [========>.....................] - ETA: 0s
[2023-05-06T00:30:30.217+0000] {logging_mixin.py:149} INFO - 52/92 [===============>..............] - ETA: 0s
[2023-05-06T00:30:30.268+0000] {logging_mixin.py:149} INFO - 74/92 [=======================>......] - ETA: 0s
[2023-05-06T00:30:30.307+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 1s 3ms/step
[2023-05-06T00:30:30.331+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=  33.5s
[2023-05-06T00:31:03.991+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 26s
[2023-05-06T00:31:04.042+0000] {logging_mixin.py:149} INFO - 18/92 [====>.........................] - ETA: 0s 
[2023-05-06T00:31:04.094+0000] {logging_mixin.py:149} INFO - 38/92 [===========>..................] - ETA: 0s
[2023-05-06T00:31:04.146+0000] {logging_mixin.py:149} INFO - 58/92 [=================>............] - ETA: 0s
[2023-05-06T00:31:04.198+0000] {logging_mixin.py:149} INFO - 79/92 [========================>.....] - ETA: 0s
[2023-05-06T00:31:04.235+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 1s 3ms/step
[2023-05-06T00:31:04.255+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=  33.9s
[2023-05-06T00:31:39.735+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 29s
[2023-05-06T00:31:39.785+0000] {logging_mixin.py:149} INFO -  8/92 [=>............................] - ETA: 0s 
[2023-05-06T00:31:39.837+0000] {logging_mixin.py:149} INFO - 24/92 [======>.......................] - ETA: 0s
[2023-05-06T00:31:39.888+0000] {logging_mixin.py:149} INFO - 47/92 [==============>...............] - ETA: 0s
[2023-05-06T00:31:39.939+0000] {logging_mixin.py:149} INFO - 72/92 [======================>.......] - ETA: 0s
[2023-05-06T00:31:39.990+0000] {logging_mixin.py:149} INFO - 90/92 [============================>.] - ETA: 0s
[2023-05-06T00:31:39.997+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 1s 3ms/step
[2023-05-06T00:31:40.023+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=  35.8s
[2023-05-06T00:32:21.283+0000] {logging_function.py:9} INFO - Grid search results: 
[2023-05-06T00:32:21.285+0000] {logging_function.py:11} INFO - Params: {'batch_size': 128, 'dropout': 0.4, 'epochs': 50, 'learning_rate': 0.0001, 'num_units': 32} - Mean test score: -0.0018181713039824691, Std test score: 0.00010271477153366303
[2023-05-06T00:32:21.289+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/fetching_best_model.py", line 50, in best_model_search
    best_model.model.save('/Users/hople/Desktop/Work_sample/dags/model/best_lstm_model.keras')
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 513, in recursive_create_dir_v2
    _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.PermissionDeniedError: /Users/hople/Desktop/Work_sample/dags; Permission denied
[2023-05-06T00:32:21.304+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=machine_learning_task, execution_date=20230506T002925, start_date=20230506T002956, end_date=20230506T003221
[2023-05-06T00:32:21.316+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 673 for task machine_learning_task (/Users/hople/Desktop/Work_sample/dags; Permission denied; 4509)
[2023-05-06T00:32:21.778+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-06T00:32:21.798+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
