[2023-05-06T19:18:56.028+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.collecting_all_metrics manual__2023-05-06T19:15:21.958093+00:00 [queued]>
[2023-05-06T19:18:56.040+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.collecting_all_metrics manual__2023-05-06T19:15:21.958093+00:00 [queued]>
[2023-05-06T19:18:56.042+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-06T19:18:56.056+0000] {taskinstance.py:1350} INFO - Executing <Task(PostgresOperator): collecting_all_metrics> on 2023-05-06 19:15:21.958093+00:00
[2023-05-06T19:18:56.069+0000] {standard_task_runner.py:57} INFO - Started process 7218 to run task
[2023-05-06T19:18:56.075+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'collecting_all_metrics', 'manual__2023-05-06T19:15:21.958093+00:00', '--job-id', '1158', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpb2l3o_kk']
[2023-05-06T19:18:56.077+0000] {standard_task_runner.py:85} INFO - Job 1158: Subtask collecting_all_metrics
[2023-05-06T19:18:56.137+0000] {task_command.py:410} INFO - Running <TaskInstance: ml_pipeline.collecting_all_metrics manual__2023-05-06T19:15:21.958093+00:00 [running]> on host 4d1b15dff216
[2023-05-06T19:18:56.234+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lequanghop844@gmail.com' AIRFLOW_CTX_DAG_OWNER='Felix Le' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='collecting_all_metrics' AIRFLOW_CTX_EXECUTION_DATE='2023-05-06T19:15:21.958093+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-06T19:15:21.958093+00:00'
[2023-05-06T19:18:56.235+0000] {sql.py:262} INFO - Executing: SELECT * FROM tracking_best_model;
[2023-05-06T19:18:56.258+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 263, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 181, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 143, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2023-05-06T19:18:56.264+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=collecting_all_metrics, execution_date=20230506T191521, start_date=20230506T191856, end_date=20230506T191856
[2023-05-06T19:18:56.274+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1158 for task collecting_all_metrics (The conn_id `postgres_default` isn't defined; 7218)
[2023-05-06T19:18:56.342+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-06T19:18:56.363+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
