[2023-05-28T16:58:58.816+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-28T16:58:16.477574+00:00 [queued]>
[2023-05-28T16:58:58.825+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-28T16:58:16.477574+00:00 [queued]>
[2023-05-28T16:58:58.826+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-28T16:58:58.837+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): machine_learning_task> on 2023-05-28 16:58:16.477574+00:00
[2023-05-28T16:58:58.846+0000] {standard_task_runner.py:57} INFO - Started process 613 to run task
[2023-05-28T16:58:58.852+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'machine_learning_task', 'manual__2023-05-28T16:58:16.477574+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmps3yvquub']
[2023-05-28T16:58:58.855+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask machine_learning_task
[2023-05-28T16:58:58.913+0000] {task_command.py:410} INFO - Running <TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-28T16:58:16.477574+00:00 [running]> on host 35c8b4e50cd6
[2023-05-28T16:58:59.002+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lequanghop844@gmail.com' AIRFLOW_CTX_DAG_OWNER='Felix Le' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='machine_learning_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-28T16:58:16.477574+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-28T16:58:16.477574+00:00'
[2023-05-28T16:58:59.472+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/joblib/parallel.py:776: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  **self._backend_args)

[2023-05-28T16:58:59.473+0000] {logging_mixin.py:149} INFO - Fitting 3 folds for each of 1 candidates, totalling 3 fits
[2023-05-28T16:59:07.053+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 23s
[2023-05-28T16:59:07.104+0000] {logging_mixin.py:149} INFO - 52/92 [===============>..............] - ETA: 0s 
[2023-05-28T16:59:07.143+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 0s 988us/step
[2023-05-28T16:59:07.169+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=   7.7s
[2023-05-28T16:59:14.930+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 19s
[2023-05-28T16:59:14.981+0000] {logging_mixin.py:149} INFO - 56/92 [=================>............] - ETA: 0s 
[2023-05-28T16:59:15.012+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 0s 898us/step
[2023-05-28T16:59:15.027+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=   7.9s
[2023-05-28T16:59:22.331+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 27s
[2023-05-28T16:59:22.382+0000] {logging_mixin.py:149} INFO - 51/92 [===============>..............] - ETA: 0s 
[2023-05-28T16:59:22.424+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 0s 1ms/step
[2023-05-28T16:59:22.440+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=   7.4s
[2023-05-28T16:59:33.196+0000] {save.py:276} WARNING - Found untraced functions such as _update_step_xla, lstm_cell_3_layer_call_fn, lstm_cell_3_layer_call_and_return_conditional_losses while saving (showing 3 of 3). These functions will not be directly callable after loading.
[2023-05-28T16:59:33.596+0000] {builder_impl.py:798} INFO - Assets written to: dags/model/best_lstm_model.SavedModel/assets
[2023-05-28T16:59:33.811+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-05-28T16:59:33.823+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=ml_pipeline, task_id=machine_learning_task, execution_date=20230528T165816, start_date=20230528T165858, end_date=20230528T165933
[2023-05-28T16:59:34.113+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-05-28T16:59:34.142+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
