[2023-05-03T05:41:57.890+0000] {processor.py:153} INFO - Started process (PID=52853) to work on /opt/airflow/dags/utils/ab.py
[2023-05-03T05:41:57.891+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/utils/ab.py for tasks to queue
[2023-05-03T05:41:57.892+0000] {logging_mixin.py:137} INFO - [2023-05-03T05:41:57.892+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/utils/ab.py
[2023-05-03T05:41:58.122+0000] {logging_mixin.py:137} INFO - [2023-05-03T05:41:58.120+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/utils/ab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/ab.py", line 6, in <module>
    from utils.data_processing import data_processing
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/Users/hople/Desktop/Work_sample/Dataset/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hople/Desktop/Work_sample/Dataset/symbols_valid_meta.csv'
[2023-05-03T05:41:58.123+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/ab.py
[2023-05-03T05:41:58.134+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/utils/ab.py took 0.246 seconds
[2023-05-03T05:42:29.105+0000] {processor.py:153} INFO - Started process (PID=52907) to work on /opt/airflow/dags/utils/ab.py
[2023-05-03T05:42:29.107+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/utils/ab.py for tasks to queue
[2023-05-03T05:42:29.109+0000] {logging_mixin.py:137} INFO - [2023-05-03T05:42:29.108+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/utils/ab.py
[2023-05-03T05:42:29.407+0000] {logging_mixin.py:137} INFO - [2023-05-03T05:42:29.404+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/utils/ab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/ab.py", line 6, in <module>
    from utils.data_processing import data_processing
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/Users/hople/Desktop/Work_sample/Dataset/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hople/Desktop/Work_sample/Dataset/symbols_valid_meta.csv'
[2023-05-03T05:42:29.409+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/ab.py
[2023-05-03T05:42:29.424+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/utils/ab.py took 0.323 seconds
[2023-05-03T05:42:59.492+0000] {processor.py:153} INFO - Started process (PID=52963) to work on /opt/airflow/dags/utils/ab.py
[2023-05-03T05:42:59.494+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/utils/ab.py for tasks to queue
[2023-05-03T05:42:59.494+0000] {logging_mixin.py:137} INFO - [2023-05-03T05:42:59.494+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/utils/ab.py
[2023-05-03T05:42:59.845+0000] {logging_mixin.py:137} INFO - [2023-05-03T05:42:59.843+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/utils/ab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/ab.py", line 6, in <module>
    from utils.data_processing import data_processing
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/Users/hople/Desktop/Work_sample/Dataset/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hople/Desktop/Work_sample/Dataset/symbols_valid_meta.csv'
[2023-05-03T05:42:59.846+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/ab.py
[2023-05-03T05:42:59.862+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/utils/ab.py took 0.372 seconds
[2023-05-03T05:43:30.678+0000] {processor.py:153} INFO - Started process (PID=53015) to work on /opt/airflow/dags/utils/ab.py
[2023-05-03T05:43:30.684+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/utils/ab.py for tasks to queue
[2023-05-03T05:43:30.685+0000] {logging_mixin.py:137} INFO - [2023-05-03T05:43:30.684+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/utils/ab.py
[2023-05-03T05:43:31.007+0000] {logging_mixin.py:137} INFO - [2023-05-03T05:43:31.004+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/utils/ab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/ab.py", line 6, in <module>
    from utils.data_processing import data_processing
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/Users/hople/Desktop/Work_sample/Dataset/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hople/Desktop/Work_sample/Dataset/symbols_valid_meta.csv'
[2023-05-03T05:43:31.007+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/ab.py
[2023-05-03T05:43:31.023+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/utils/ab.py took 0.348 seconds
[2023-05-03T05:44:01.204+0000] {processor.py:153} INFO - Started process (PID=53067) to work on /opt/airflow/dags/utils/ab.py
[2023-05-03T05:44:01.205+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/utils/ab.py for tasks to queue
[2023-05-03T05:44:01.207+0000] {logging_mixin.py:137} INFO - [2023-05-03T05:44:01.207+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/utils/ab.py
[2023-05-03T05:44:01.476+0000] {logging_mixin.py:137} INFO - [2023-05-03T05:44:01.473+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/utils/ab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/ab.py", line 6, in <module>
    from utils.data_processing import data_processing
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/Users/hople/Desktop/Work_sample/Dataset/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hople/Desktop/Work_sample/Dataset/symbols_valid_meta.csv'
[2023-05-03T05:44:01.477+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/ab.py
[2023-05-03T05:44:01.490+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/utils/ab.py took 0.293 seconds
[2023-05-03T05:44:31.695+0000] {processor.py:153} INFO - Started process (PID=53119) to work on /opt/airflow/dags/utils/ab.py
[2023-05-03T05:44:31.696+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/utils/ab.py for tasks to queue
[2023-05-03T05:44:31.697+0000] {logging_mixin.py:137} INFO - [2023-05-03T05:44:31.697+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/utils/ab.py
[2023-05-03T05:44:31.985+0000] {logging_mixin.py:137} INFO - [2023-05-03T05:44:31.982+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/utils/ab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/ab.py", line 6, in <module>
    from utils.data_processing import data_processing
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/Users/hople/Desktop/Work_sample/Dataset/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hople/Desktop/Work_sample/Dataset/symbols_valid_meta.csv'
[2023-05-03T05:44:31.986+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/ab.py
[2023-05-03T05:44:32.000+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/utils/ab.py took 0.309 seconds
[2023-05-03T05:45:02.143+0000] {processor.py:153} INFO - Started process (PID=53171) to work on /opt/airflow/dags/utils/ab.py
[2023-05-03T05:45:02.144+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/utils/ab.py for tasks to queue
[2023-05-03T05:45:02.145+0000] {logging_mixin.py:137} INFO - [2023-05-03T05:45:02.145+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/utils/ab.py
[2023-05-03T05:45:02.412+0000] {logging_mixin.py:137} INFO - [2023-05-03T05:45:02.408+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/utils/ab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/ab.py", line 6, in <module>
    from utils.data_processing import data_processing
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/Users/hople/Desktop/Work_sample/Dataset/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hople/Desktop/Work_sample/Dataset/symbols_valid_meta.csv'
[2023-05-03T05:45:02.412+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/ab.py
[2023-05-03T05:45:02.430+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/utils/ab.py took 0.290 seconds
[2023-05-03T05:45:32.556+0000] {processor.py:153} INFO - Started process (PID=53223) to work on /opt/airflow/dags/utils/ab.py
[2023-05-03T05:45:32.559+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/utils/ab.py for tasks to queue
[2023-05-03T05:45:32.560+0000] {logging_mixin.py:137} INFO - [2023-05-03T05:45:32.560+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/utils/ab.py
[2023-05-03T05:45:32.848+0000] {logging_mixin.py:137} INFO - [2023-05-03T05:45:32.845+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/utils/ab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/ab.py", line 6, in <module>
    from utils.data_processing import data_processing
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/Users/hople/Desktop/Work_sample/Dataset/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hople/Desktop/Work_sample/Dataset/symbols_valid_meta.csv'
[2023-05-03T05:45:32.849+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/ab.py
[2023-05-03T05:45:32.862+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/utils/ab.py took 0.312 seconds
[2023-05-03T05:46:03.257+0000] {processor.py:153} INFO - Started process (PID=53275) to work on /opt/airflow/dags/utils/ab.py
[2023-05-03T05:46:03.259+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/utils/ab.py for tasks to queue
[2023-05-03T05:46:03.260+0000] {logging_mixin.py:137} INFO - [2023-05-03T05:46:03.260+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/utils/ab.py
[2023-05-03T05:46:03.548+0000] {logging_mixin.py:137} INFO - [2023-05-03T05:46:03.546+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/utils/ab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/utils/ab.py", line 6, in <module>
    from utils.data_processing import data_processing
  File "/opt/airflow/dags/utils/data_processing.py", line 1, in <module>
    from utils.add_symbol_serName import add_name
  File "/opt/airflow/dags/utils/add_symbol_serName.py", line 5, in <module>
    metal_symbol = pd.read_csv('/Users/hople/Desktop/Work_sample/Dataset/symbols_valid_meta.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/Users/hople/Desktop/Work_sample/Dataset/symbols_valid_meta.csv'
[2023-05-03T05:46:03.549+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/utils/ab.py
[2023-05-03T05:46:03.562+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/utils/ab.py took 0.312 seconds
