[2023-05-06T00:29:12.578+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-06T00:28:12.186553+00:00 [queued]>
[2023-05-06T00:29:12.660+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-06T00:28:12.186553+00:00 [queued]>
[2023-05-06T00:29:12.662+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-06T00:29:12.783+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): machine_learning_task> on 2023-05-06 00:28:12.186553+00:00
[2023-05-06T00:29:12.866+0000] {standard_task_runner.py:57} INFO - Started process 3364 to run task
[2023-05-06T00:29:12.895+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'machine_learning_task', 'manual__2023-05-06T00:28:12.186553+00:00', '--job-id', '648', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpljc_k15w']
[2023-05-06T00:29:12.898+0000] {standard_task_runner.py:85} INFO - Job 648: Subtask machine_learning_task
[2023-05-06T00:29:13.179+0000] {task_command.py:410} INFO - Running <TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-06T00:28:12.186553+00:00 [running]> on host 29d8848a13b4
[2023-05-06T00:29:13.420+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lequanghop844@gmail.com' AIRFLOW_CTX_DAG_OWNER='Felix Le' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='machine_learning_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-06T00:28:12.186553+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-06T00:28:12.186553+00:00'
[2023-05-06T00:29:14.377+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/joblib/parallel.py:776: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  **self._backend_args)

[2023-05-06T00:29:14.382+0000] {logging_mixin.py:149} INFO - Fitting 3 folds for each of 1 candidates, totalling 3 fits
[2023-05-06T00:30:07.258+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 39s
[2023-05-06T00:30:07.309+0000] {logging_mixin.py:149} INFO - 19/92 [=====>........................] - ETA: 0s 
[2023-05-06T00:30:07.360+0000] {logging_mixin.py:149} INFO - 39/92 [===========>..................] - ETA: 0s
[2023-05-06T00:30:07.413+0000] {logging_mixin.py:149} INFO - 61/92 [==================>...........] - ETA: 0s
[2023-05-06T00:30:07.463+0000] {logging_mixin.py:149} INFO - 84/92 [==========================>...] - ETA: 0s
[2023-05-06T00:30:07.482+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 1s 2ms/step
[2023-05-06T00:30:07.508+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=  53.1s
[2023-05-06T00:30:40.445+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 31s
[2023-05-06T00:30:40.496+0000] {logging_mixin.py:149} INFO - 18/92 [====>.........................] - ETA: 0s 
[2023-05-06T00:30:40.547+0000] {logging_mixin.py:149} INFO - 36/92 [==========>...................] - ETA: 0s
[2023-05-06T00:30:40.597+0000] {logging_mixin.py:149} INFO - 54/92 [================>.............] - ETA: 0s
[2023-05-06T00:30:40.648+0000] {logging_mixin.py:149} INFO - 72/92 [======================>.......] - ETA: 0s
[2023-05-06T00:30:40.699+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - ETA: 0s
[2023-05-06T00:30:40.702+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 1s 3ms/step
[2023-05-06T00:30:40.719+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=  33.2s
[2023-05-06T00:31:14.538+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 34s
[2023-05-06T00:31:14.591+0000] {logging_mixin.py:149} INFO - 17/92 [====>.........................] - ETA: 0s 
[2023-05-06T00:31:14.643+0000] {logging_mixin.py:149} INFO - 36/92 [==========>...................] - ETA: 0s
[2023-05-06T00:31:14.694+0000] {logging_mixin.py:149} INFO - 56/92 [=================>............] - ETA: 0s
[2023-05-06T00:31:14.746+0000] {logging_mixin.py:149} INFO - 75/92 [=======================>......] - ETA: 0s
[2023-05-06T00:31:14.783+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 1s 3ms/step
[2023-05-06T00:31:14.801+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=  34.1s
[2023-05-06T00:32:03.155+0000] {logging_function.py:9} INFO - Grid search results: 
[2023-05-06T00:32:03.159+0000] {logging_function.py:11} INFO - Params: {'batch_size': 128, 'dropout': 0.4, 'epochs': 50, 'learning_rate': 0.0001, 'num_units': 32} - Mean test score: -0.0018110511218775063, Std test score: 0.0001118450995653908
[2023-05-06T00:32:03.165+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/fetching_best_model.py", line 50, in best_model_search
    best_model.model.save('/Users/hople/Desktop/Work_sample/dags/model/best_lstm_model.keras')
  File "/home/airflow/.local/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/airflow/.local/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 513, in recursive_create_dir_v2
    _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.PermissionDeniedError: /Users/hople/Desktop/Work_sample/dags; Permission denied
[2023-05-06T00:32:03.188+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=ml_pipeline, task_id=machine_learning_task, execution_date=20230506T002812, start_date=20230506T002912, end_date=20230506T003203
[2023-05-06T00:32:03.208+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 648 for task machine_learning_task (/Users/hople/Desktop/Work_sample/dags; Permission denied; 3364)
[2023-05-06T00:32:04.016+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-06T00:32:04.060+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
