[2023-05-07T06:17:36.933+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-07T06:17:08.037375+00:00 [queued]>
[2023-05-07T06:17:36.940+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-07T06:17:08.037375+00:00 [queued]>
[2023-05-07T06:17:36.941+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2023-05-07T06:17:36.952+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): machine_learning_task> on 2023-05-07 06:17:08.037375+00:00
[2023-05-07T06:17:36.963+0000] {standard_task_runner.py:57} INFO - Started process 27236 to run task
[2023-05-07T06:17:36.968+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline', 'machine_learning_task', 'manual__2023-05-07T06:17:08.037375+00:00', '--job-id', '1256', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmp7gf4_tco']
[2023-05-07T06:17:36.969+0000] {standard_task_runner.py:85} INFO - Job 1256: Subtask machine_learning_task
[2023-05-07T06:17:37.014+0000] {task_command.py:410} INFO - Running <TaskInstance: ml_pipeline.machine_learning_task manual__2023-05-07T06:17:08.037375+00:00 [running]> on host 4d1b15dff216
[2023-05-07T06:17:37.116+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='lequanghop844@gmail.com' AIRFLOW_CTX_DAG_OWNER='Felix Le' AIRFLOW_CTX_DAG_ID='ml_pipeline' AIRFLOW_CTX_TASK_ID='machine_learning_task' AIRFLOW_CTX_EXECUTION_DATE='2023-05-07T06:17:08.037375+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-07T06:17:08.037375+00:00'
[2023-05-07T06:17:37.301+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/joblib/parallel.py:776: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  **self._backend_args)

[2023-05-07T06:17:37.301+0000] {logging_mixin.py:149} INFO - Fitting 3 folds for each of 1 candidates, totalling 3 fits
[2023-05-07T06:17:42.268+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 17s
[2023-05-07T06:17:42.318+0000] {logging_mixin.py:149} INFO - 76/92 [=======================>......] - ETA: 0s 
[2023-05-07T06:17:42.328+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 0s 665us/step
[2023-05-07T06:17:42.344+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=   5.0s
[2023-05-07T06:17:47.812+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 13s
[2023-05-07T06:17:47.862+0000] {logging_mixin.py:149} INFO - 82/92 [=========================>....] - ETA: 0s 
[2023-05-07T06:17:47.869+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 0s 629us/step
[2023-05-07T06:17:47.880+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=   5.5s
[2023-05-07T06:17:53.024+0000] {logging_mixin.py:149} INFO -  1/92 [..............................] - ETA: 18s
[2023-05-07T06:17:53.074+0000] {logging_mixin.py:149} INFO - 71/92 [======================>.......] - ETA: 0s 
[2023-05-07T06:17:53.091+0000] {logging_mixin.py:149} INFO - 92/92 [==============================] - 0s 738us/step
[2023-05-07T06:17:53.103+0000] {logging_mixin.py:149} INFO - [CV] END batch_size=128, dropout=0.4, epochs=50, learning_rate=0.0001, num_units=32; total time=   5.2s
[2023-05-07T06:18:01.373+0000] {save.py:276} WARNING - Found untraced functions such as _update_step_xla, lstm_cell_3_layer_call_fn, lstm_cell_3_layer_call_and_return_conditional_losses while saving (showing 3 of 3). These functions will not be directly callable after loading.
[2023-05-07T06:18:01.641+0000] {builder_impl.py:798} INFO - Assets written to: /Users/hople/Desktop/Work_sample/model/best_lstm_model/assets
[2023-05-07T06:18:01.812+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-05-07T06:18:01.828+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=ml_pipeline, task_id=machine_learning_task, execution_date=20230507T061708, start_date=20230507T061736, end_date=20230507T061801
[2023-05-07T06:18:02.128+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-05-07T06:18:02.154+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
